apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-base
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql-esp-news
          image: cheikht/mysql_esp_news
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: news
            - name: DATABASE_USER
              value: root
            - name: DATABASE_HOST
              value: db
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"